# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'third-party/qtkeychain': '@latest'

- 'on': ['Linux/Qt6', 'FreeBSD/Qt6', 'Windows/Qt6']
  'require':
    'frameworks/extra-cmake-modules': '@latest-qt6'
    'frameworks/kcoreaddons': '@latest-kf6'
    'frameworks/kwidgetsaddons': '@latest-kf6'
    'frameworks/kdbusaddons': '@latest-kf6'
    'frameworks/knotifications': '@latest-kf6'
    'frameworks/kconfig': '@latest-kf6'
    'frameworks/ki18n': '@latest-kf6'
    'frameworks/kio': '@latest-kf6'
    'frameworks/kwindowsystem': '@latest-kf6'
    'frameworks/kdoctools': '@latest-kf6'
    'frameworks/knewstuff': '@latest-kf6'
    'frameworks/kxmlgui': '@latest-kf6'
    'frameworks/purpose': '@latest-kf6'
    'frameworks/kguiaddons': '@latest-kf6'
    'frameworks/kitemviews': '@latest-kf6'
    'frameworks/kiconthemes': '@latest-kf6'
    'frameworks/sonnet': '@latest-kf6'
    'frameworks/ktextwidgets': '@latest-kf6'
    'frameworks/syntax-highlighting': '@latest-kf6'
    'frameworks/prison' : '@latest-kf6'
    'frameworks/kidletime': '@latest-kf6'
    'frameworks/knotifyconfig': '@latest-kf6'
    'frameworks/breeze-icons': '@latest-kf6'
    'frameworks/karchive': '@latest-kf6'
    'frameworks/kstatusnotifieritem': '@latest-kf6'
    'frameworks/kuserfeedback': '@latest-kf6'
    'libraries/ktextaddons': '@latest-kf6'

- 'on': ['Linux/Qt6']
  'require':
    'sdk/selenium-webdriver-at-spi': '@latest-kf6'

