version = 1
SPDX-PackageName = "ruqola"
SPDX-PackageSupplier = "Montel Laurent <montel@kde.org>"
SPDX-PackageDownloadLocation = "https://invent.kde.org/network/ruqola"

[[annotations]]
path = ["src/core/autotests/data/room-update-subscription/**.json", "src/core/autotests/data/room-update-subscription/**.ref", "src/core/autotests/data/room-updated/**.json", "src/core/autotests/data/room-updated/**.ref", "src/core/autotests/data/method/**.ref", "src/core/autotests/data/**/**.json", "src/core/autotests/data/**/**.ref", "distro/**", "development/TODO", "src/core/autotests/data/downloadappslanguages/**", "readme-build-ftime.txt"]
precedence = "aggregate"
SPDX-FileCopyrightText = "none"
SPDX-License-Identifier = "CC0-1.0"
